FROM registry.redhat.io/rhel10/rhel-bootc:latest

# Install extended network, storage, firmware, and IPMI tools
RUN microdnf install -y \
    python3 python3-pip ansible-core \
    openssh-clients openssh-server \
    iproute ethtool iputils net-tools bridge-utils \
    teamd lldpd ipmitool \
    nmap tcpdump bind-utils wireshark-cli \
    lshw mdadm e2fsprogs xfsprogs exfatprogs btrfs-progs \
    procps-ng dnstop \
    lvm2 smartmontools nvme-cli dmidecode util-linux \
    curl wget iperf iperf3 nmstate \
    && microdnf clean all

FROM registry.redhat.io/rhel10/rhel-bootc:latest

RUN microdnf install -y \
    python3 python3-pip ansible-core \
    openssh-clients openssh-server \
    iproute ethtool iputils net-tools bridge-utils \
    teamd lldpd ipmitool tmux which \
    nmap tcpdump bind-utils wireshark-cli \
    mdadm e2fsprogs xfsprogs exfatprogs btrfs-progs \
    procps-ng dnstop vim lshw fwupd \
    pciutils usbutils hwinfo tpm-tools \
    lvm2 smartmontools nvme-cli dmidecode util-linux \
    curl wget iperf iperf3 nmstate open-vm-tools \
    scapy ngrep netsniff-ng ettercap \
    && microdnf clean all

# Dev/Compilation deps?
# gcc python3-devel  

# Enable services
RUN systemctl enable sshd.service lldpd.service

# Create Ansible user
RUN useradd -m ansible \
    && echo "ansible ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible \
    && mkdir -p /home/ansible/.ssh \
    && chmod 700 /home/ansible/.ssh

ENTRYPOINT ["/usr/sbin/init"]
